/**
 * Traduction française des codes d'action bruts stockés dans ActivityLog
 * (ex: "prospect.created"). Un seul point de vérité partagé par toutes les
 * vues qui affichent un fil d'activité (fiches client/prospect/devis/RDV,
 * tableau de bord, journal d'activité CRM et admin) afin qu'aucune ne laisse
 * fuiter un code brut à l'écran.
 */
export const ACTIVITY_ACTION_LABELS: Record<string, string> = {
  "appointment.created": "Rendez-vous créé",
  "appointment.deleted": "Rendez-vous supprimé",
  "appointment.public_booking": "Rendez-vous pris en ligne",
  "appointment.report_submitted": "Compte-rendu de RDV enregistré",
  "appointment.status_changed": "Statut du RDV modifié",
  "appointment.updated": "Rendez-vous modifié",
  "automation.rule_created": "Règle d'automatisation créée",
  "automation.rule_deleted": "Règle d'automatisation supprimée",
  "automation.rule_updated": "Règle d'automatisation modifiée",
  "automation.sweep_run": "Automatisations exécutées",
  "automation.task_created": "Tâche créée automatiquement",
  "availability_exception.created": "Exception de disponibilité créée",
  "availability_exception.deleted": "Exception de disponibilité supprimée",
  "availability_rule.created": "Règle de disponibilité créée",
  "availability_rule.deleted": "Règle de disponibilité supprimée",
  "chantier.assignment_removed": "Affectation chantier retirée",
  "chantier.assignment_updated": "Affectation chantier modifiée",
  "chantier.created": "Chantier créé",
  "chantier.deleted": "Chantier supprimé",
  "chantier.updated": "Chantier modifié",
  "client.contact_added": "Contact ajouté",
  "client.created": "Client créé",
  "client.deleted": "Client supprimé",
  "client.updated": "Fiche client mise à jour",
  "crm.created": "CRM créé",
  "crm.updated": "CRM modifié",
  "document.created": "Document ajouté",
  "document.deleted": "Document supprimé",
  "opportunity.created": "Opportunité créée",
  "opportunity.deleted": "Opportunité supprimée",
  "opportunity.stage_changed": "Étape du pipeline modifiée",
  "opportunity.updated": "Opportunité modifiée",
  "pipeline_stage.created": "Étape de pipeline créée",
  "pipeline_stage.deleted": "Étape de pipeline supprimée",
  "pointage.client_sheet_deposited": "Fiche de pointage client déposée",
  "pointage.employee_sheets_deposited": "Fiches de pointage salariés déposées",
  "pointage.employee_sheets_emailed": "Fiches de pointage envoyées par email",
  "pointage.entry_saved": "Pointage enregistré",
  "pointage.timesheet_document_deleted": "Document de pointage supprimé",
  "prospect.contact_added": "Contact ajouté",
  "prospect.converted": "Converti en client",
  "prospect.created": "Prospect créé",
  "prospect.deleted": "Prospect supprimé",
  "prospect.updated": "Fiche prospect mise à jour",
  "quote.created": "Devis créé",
  "quote.deleted": "Devis supprimé",
  "quote.pdf_generated": "PDF du devis généré",
  "quote.sent": "Devis envoyé",
  "quote.status_changed": "Statut du devis modifié",
  "quote.updated": "Devis mis à jour",
  "task.created": "Tâche créée",
  "task.deleted": "Tâche supprimée",
  "user.access_updated": "Accès utilisateur modifié",
  "user.activity_history_deleted": "Historique d'activité supprimé",
  "user.created": "Utilisateur créé",
  "user.disabled": "Utilisateur désactivé",
  "user.password_regenerated": "Mot de passe régénéré",
  "user.password_set": "Mot de passe défini",
  "user.reactivated": "Utilisateur réactivé",
  "vault.document_added": "Document déposé au coffre-fort",
  "vault.document_deleted": "Document du coffre-fort supprimé",
};

/** Traduit un code d'action ActivityLog ; retombe sur le code brut si jamais un nouveau type d'action n'a pas encore été ajouté ci-dessus. */
export function translateActivityAction(action: string): string {
  return ACTIVITY_ACTION_LABELS[action] ?? action;
}
